# Generated by Django 4.0.5 on 2022-06-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='core.discount'),
        ),
    ]
