# Generated by Django 4.0.5 on 2022-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderdetail_paymentdetail_userpayment_useraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='accountNo',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='provider',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
