# Generated by Django 4.0.5 on 2022-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userpayment_accountno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='accountNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
